# Generated by Django 3.1.2 on 2020-11-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50, unique=True)),
                ('participant_photo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
