# Generated by Django 3.1.2 on 2020-12-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=1608601376389, max_length=50, unique=True)),
                ('participant_photo', models.ImageField(upload_to='images/')),
                ('faces_location_arr', models.CharField(blank=True, max_length=200)),
                ('face_count', models.IntegerField(blank=True, default=0)),
                ('participant_faces', models.ImageField(blank=True, upload_to='images/faces')),
                ('participant_blur', models.ImageField(blank=True, upload_to='images/blur')),
                ('participant_pixel', models.ImageField(blank=True, upload_to='images/pixel')),
                ('participant_deepfake', models.ImageField(blank=True, upload_to='images/deppfake')),
            ],
        ),
    ]
