# Generated by Django 3.1.2 on 2020-12-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfuscator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.CharField(default=1608601383604, max_length=50, unique=True),
        ),
    ]
