# Generated by Django 3.1.2 on 2020-12-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obfuscator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_deepfake',
            field=models.ImageField(blank=True, upload_to='images/deepfake'),
        ),
    ]
