# Generated by Django 3.1.2 on 2020-12-22 19:21

from django.db import migrations, models
import obfuscator.models


class Migration(migrations.Migration):

    dependencies = [
        ('obfuscator', '0002_auto_20201222_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.CharField(max_length=50, unique=True, validators=[obfuscator.models.is_positive]),
        ),
    ]
